#!/usr/bin/env bash
# =============================================================================
# Example 4: Train on multiple Visium + multiple Xenium samples
#            (3-phase sequential + CDAN cross-patient domain adaptation)
#
# Training paradigm:
#   Phase 0 (Recon):   reconstruction pretraining        (15 epochs)
#   Phase 1 (Visium):  MSE on RCTD soft proportions      (100 epochs)
#                      + CDAN adversarial loss (adv_lambda=0.005)
#   Phase 2 (Xenium):  CE fine-tuning on hard labels     (100 epochs)
#
# CDAN aligns patient-level domains (each WSI = one domain) so the encoder
# learns patient-invariant features.
# VIS_S2 is held out as an out-of-sample monitor during training.
#
# Expected input layout:
#   /project/KidneyHE/01_meowcat_test/04_multi_visium_xenium/input/
#     VIS_S1/                        <- Visium patient 1
#       he_raw.tif
#       filtered_feature_bc_matrix/
#       spatial/                     <- scalefactors_json.json + tissue_positions
#     VIS_S2/                        <- Visium patient 2 (also OOS monitor)
#       ... (same layout as VIS_S1)
#     XEN_S1/                        <- Xenium patient 1
#       he_raw.tif
#       adata_cellbin_HistoSweep.h5ad
#       XEN_S1_cell_type_anno.csv
#       anno-names.txt
#     XEN_S2/                        <- Xenium patient 2
#       ... (same layout as XEN_S1)
#
# Generated by the pipeline (do NOT create manually):
#   Step 1 (meowcat rctd):       VIS_*/deconvolution_rctd/major_prop.csv
#   Step 3 (meowcat preprocess): VIS_*/anno-names.txt, anno_matrix.tsv,
#                                locs.tsv, radius.txt, pixel-size.txt
#
# Expected output layout:
#   /project/KidneyHE/01_meowcat_test/04_multi_visium_xenium/output/
#     mask/
#     batches/
#       batch_vis_000_x/y/d.npy      <- VIS_S1 (domain 0)
#       batch_vis_001_x/y/d.npy      <- VIS_S2 (domain 1)
#       batch_xen_000_x/y/d.npy      <- XEN_S1 (domain 2)
#       batch_xen_001_x/y/d.npy      <- XEN_S2 (domain 3)
#       oos_batch/                   <- OOS monitoring batches for VIS_S2
#       states/00/model.ckpt
#       states/01/model.ckpt
#     VIS_S1/  VIS_S2/  XEN_S1/  XEN_S2/
#       embeddings-hist.pickle
#       pred_fullgrid_outputs.pkl
#     results_ex04.pptx
# =============================================================================

set -euo pipefail

CFG="$(dirname "$0")/config.yaml"

echo "============================================"
echo " MeowCat Example 4: Multi-sample Visium + Xenium"
echo " Config: $CFG"
echo "============================================"

# ---------------------------------------------------------------------------
# Step 1: RCTD deconvolution for both Visium samples
# Activate: conda activate RCTD
# ---------------------------------------------------------------------------
echo "[Step 1] RCTD deconvolution (Visium samples)"
echo "  NOTE: Set rctd.reference_rds in $CFG to your single-cell reference RDS"
# meowcat rctd --config "$CFG"

# ---------------------------------------------------------------------------
# Step 2: Resolution check
# Activate: micromamba activate rapids_singlecell
# ---------------------------------------------------------------------------
echo "[Step 2] Resolution check"
meowcat check-resolution --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3: Preprocess all four samples
# Can run in parallel on a cluster (one job per sample).
# Activate: micromamba activate rapids_singlecell
# ---------------------------------------------------------------------------
# Preprocess Visium samples (auto-discovered from project.sample_pattern: "VIS*")
echo "[Step 3a] Image preprocessing — Visium samples"
meowcat preprocess --config "$CFG"

# Preprocess Xenium samples (override sample_pattern with --samples)
# Replace XEN_S1,XEN_S2 with your actual Xenium folder names.
echo "[Step 3b] Image preprocessing — Xenium samples"
meowcat preprocess --config "$CFG" --samples XEN_S1,XEN_S2

# ---------------------------------------------------------------------------
# Step 4a: Build Visium training batches
# Domain IDs are auto-assigned (one per WSI folder) unless domain_map_tsv is set.
#   domain 0 -> VIS_S1, domain 1 -> VIS_S2
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 4a] Visium batch preparation"
meowcat prepare-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 4b: Build Xenium training batches
# Xenium domain IDs continue after Visium (set via xenium.visium_batch_dir):
#   domain 2 -> XEN_S1, domain 3 -> XEN_S2
# The CDAN adversarial head will align across all 4 domains.
# ---------------------------------------------------------------------------
echo "[Step 4b] Xenium batch preparation"
meowcat prepare-xenium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 5: Train — 3-phase + CDAN
# Activate: conda activate he_anno
# Phase 0 (15 ep):   reconstruction pretraining
# Phase 1 (100 ep):  Visium MSE + CDAN domain adversarial (adv_lambda=0.005)
#   VIS_S2 is monitored as out-of-sample via --oos-sample (no gradient leak)
# Phase 2 (100 ep):  Xenium CE fine-tuning (xenium_weight=0.01)
# ---------------------------------------------------------------------------
echo "[Step 5] Training (Recon -> Visium+CDAN -> Xenium)"
meowcat train --config "$CFG"

# ---------------------------------------------------------------------------
# Step 6: Predict and visualize on all samples
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 6] Prediction — all samples"
meowcat predict --config "$CFG"

echo "[Step 6] Visualization — all samples"
meowcat visualize --config "$CFG"

# ---------------------------------------------------------------------------
# Step 7: Generate PowerPoint summary
# ---------------------------------------------------------------------------
echo "[Step 7] Slide wrap"
meowcat slide --config "$CFG"

echo "============================================"
echo " Done. Outputs: /project/KidneyHE/01_meowcat_test/04_multi_visium_xenium/output/"
echo "============================================"
