#!/usr/bin/env bash
# =============================================================================
# Example 5: Train on multiple Visium + multiple Xenium samples
#            (3-phase sequential + CDAN cross-patient domain adaptation)
#
# Training paradigm:
#   Phase 0 (Recon):   reconstruction pretraining        (15 epochs)
#   Phase 1 (Visium):  MSE on RCTD soft proportions      (100 epochs)
#                      + CDAN adversarial loss (adv_lambda=0.005)
#   Phase 2 (Xenium):  CE fine-tuning on hard labels     (100 epochs)
#
# CDAN aligns patient-level domains (each WSI = one domain) so the encoder
# learns patient-invariant features.
#
# Expected input layout (demo: 4 LUAD patients P11/P17/P19/P24):
#   <data_root>/
#     P11_LUAD/                        <- Visium patient
#       he_raw.tif
#       filtered_feature_bc_matrix/
#       spatial/                       <- scalefactors_json.json + tissue_positions
#       deconvolution_rctd/major_prop.csv   <- pre-computed RCTD (bundled in demo)
#       pixel-size-raw.txt             <- 0.2513 µm/px (bundled in demo)
#     P17_LUAD/  P19_LUAD/  P24_LUAD/  ... (same layout)
#     P11_LUAD_Xenium/                 <- Xenium patient
#       he_raw.tif                     <- raw H&E image
#       xenium_raw/                    <- cell_feature_matrix.h5 + cells.parquet
#       adata_cellbin_HistoSweep.h5ad  <- cell-bin location mapping (slimmed in demo)
#       annotation.csv                 <- cell type annotations (cell_id, cell_state)
#       pixel-size-raw.txt             <- 0.5 µm/px (bundled in demo)
#     P17_LUAD_Xenium/  P19_LUAD_Xenium/  P24_LUAD_Xenium/  ... (same layout)
#   anno-names.txt                     <- cell type order (referenced by xenium.anno_names_path)
#
# Generated by the pipeline (do NOT create manually):
#   Step 3 (meowcat preprocess): <SAMPLE>/single_super_emb.h5ad
#   Step 3.5 (meowcat prepare-visium): VIS samples' anno_matrix.tsv / locs.tsv / radius.txt
#
# Expected output layout:
#   <out_root>/
#     mask/
#     batches/
#       batch_vis_000_x/y/d.npy      <- Visium sample 1 (domain 0)
#       batch_vis_001_x/y/d.npy      <- Visium sample 2 (domain 1)
#       ...
#       batch_xen_000_x/y/d.npy      <- Xenium sample 1 (domain N)
#       batch_xen_001_x/y/d.npy      <- Xenium sample 2 (domain N+1)
#       ...
#       states/00/model.ckpt
#       states/01/model.ckpt
#     P11_LUAD/ ... P11_LUAD_Xenium/ ...
#       embeddings-hist.pickle or .npy
#       pred_fullgrid_outputs.pkl
#     results_ex05.pptx
#
# Usage:
#   conda activate he_anno
#   bash run.sh > log.txt 2>&1 &
# =============================================================================
set -euo pipefail
export PYTHONWARNINGS="ignore"

CFG="$(dirname "$0")/config.yaml"

echo "============================================"
echo " MeowCat Example 5: Multi-sample Visium + Xenium"
echo " Config: $CFG"
echo "============================================"

# ---------------------------------------------------------------------------
# Step 1: RCTD deconvolution for both Visium samples
# Skipped: the Zenodo demo bundle ships deconvolution_rctd/major_prop.csv per
# Visium sample, so this step is unnecessary. For NEW samples (not the demo),
# uncomment the two lines below and set rctd.reference_rds in the config.
# ---------------------------------------------------------------------------
# echo "[Step 1] RCTD deconvolution (Visium samples)"
# meowcat rctd --config "$CFG"

# ---------------------------------------------------------------------------
# Step 2: Resolution check
# Skipped: the Zenodo demo bundle ships pixel-size-raw.txt per sample.
# For new samples: if you know the H&E resolution, write it (in µm/px) into
# pixel-size-raw.txt in each sample folder. If you DO NOT know it and your
# image is a TIF with embedded resolution metadata, uncomment the following
# code to auto-detect.
# ---------------------------------------------------------------------------
# echo "[Step 2] Resolution check"
# meowcat check-resolution --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3: Preprocess all images (data-agnostic — works for both Visium and Xenium)
# Auto-discovers both VIS* and XEN* samples from data_root.
# Can run in parallel on a cluster (one job per sample).
# Activate: conda activate he_anno
# Produces single_super_emb.h5ad (UNI histology features) per sample.
# For Xenium, prepare-xenium-batches (Step 4b) will automatically merge
# histology features from single_super_emb.h5ad into the cellbin.
# ---------------------------------------------------------------------------
echo "[Step 3] Image preprocessing — all samples (VIS* + XEN*)"
meowcat preprocess --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3.5: Prepare Visium metadata + embeddings
# Creates: anno-names.txt, anno_matrix.tsv, locs.tsv, radius.txt,
#          pixel-size.txt, embeddings-hist.pickle or .npy
# ---------------------------------------------------------------------------
echo "[Step 3.5] Visium metadata preparation"
meowcat prepare-visium --config "$CFG"

# ---------------------------------------------------------------------------
# Step 4a: Build Visium training batches
# Domain IDs are auto-assigned alphabetically (one per WSI folder) unless
# domain_map_tsv is set. For the demo: P11_LUAD=0, P17_LUAD=1, P19_LUAD=2,
# P24_LUAD=3.
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 4a] Visium batch preparation"
meowcat prepare-visium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 4b: Build Xenium training batches
# Xenium domain IDs continue after Visium (set via xenium.visium_batch_dir).
# For the demo: P11_LUAD_Xenium=4, P17_LUAD_Xenium=5, P19_LUAD_Xenium=6,
# P24_LUAD_Xenium=7. The CDAN adversarial head aligns across all 8 domains.
# ---------------------------------------------------------------------------
echo "[Step 4b] Xenium batch preparation"
meowcat prepare-xenium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 5: Train — 3-phase + CDAN
# Activate: conda activate he_anno
# Phase 0 (15 ep):   reconstruction pretraining
# Phase 1 (100 ep):  Visium MSE + CDAN domain adversarial (adv_lambda=0.005)
#   To enable out-of-sample monitoring, set train.oos_sample in the config.
# Phase 2 (100 ep):  Xenium CE fine-tuning (xenium_weight=0.01)
# ---------------------------------------------------------------------------
echo "[Step 5] Training (Recon -> Visium+CDAN -> Xenium)"
meowcat train --config "$CFG"

# ---------------------------------------------------------------------------
# Step 6: Predict and visualize on all samples
# Activate: conda activate he_anno
# Auto-discovers both VIS* and XEN* samples from data_root.
# To override: meowcat predict --config "$CFG" --samples P11_LUAD,P11_LUAD_Xenium,...
# ---------------------------------------------------------------------------
echo "[Step 6] Prediction — all samples"
meowcat predict --config "$CFG"

echo "[Step 6] Visualization — all samples"
meowcat visualize --config "$CFG"

# ---------------------------------------------------------------------------
# Step 7: Generate PowerPoint summary
# ---------------------------------------------------------------------------
echo "[Step 7] Slide wrap"
meowcat slide --config "$CFG"

echo "============================================"
echo " Done. Outputs: <DEMO_DATA_ROOT>/05_multi_visium_xenium/output/"
echo "============================================"
