#!/usr/bin/env bash
# =============================================================================
# Example 3: Train on one Visium + one Xenium sample (3-phase sequential)
#
# Training paradigm:
#   Phase 0 (Recon):   reconstruction pretraining        (15 epochs)
#   Phase 1 (Visium):  MSE on RCTD soft proportions      (100 epochs)
#   Phase 2 (Xenium):  CE fine-tuning on hard labels     (50 epochs)
#
# The Xenium phase fine-tunes the encoder trained on Visium, transferring
# spot-level spatial knowledge to single-cell resolution.
#
# Expected input layout:
#   /project/KidneyHE/01_meowcat_test/03_visium_xenium_single/input/
#     VIS_P11_LUAD/
#       he_raw.tif
#       filtered_feature_bc_matrix/
#       spatial/                       <- scalefactors_json.json + tissue_positions
#     XEN_P11_LUAD/
#       he_raw.tif                     <- raw H&E image
#       xenium_raw/                    <- 10x Xenium output
#       adata_cellbin_HistoSweep.h5ad  <- cell-bin location mapping (external HistoSweep)
#       annotation.csv                 <- cell type annotations
#
# Generated by the pipeline (do NOT create manually):
#   Step 1  (meowcat rctd):       VIS_P11_LUAD/deconvolution_rctd/major_prop.csv
#   Step 3a (meowcat preprocess): VIS_P11_LUAD/anno-names.txt, anno_matrix.tsv,
#                                 locs.tsv, radius.txt, pixel-size.txt
#
# Expected output layout:
#   /project/KidneyHE/01_meowcat_test/03_visium_xenium_single/output/
#     mask/
#     batches/
#       batch_vis_000_x/y/d.npy        <- Visium batches (resolution=0, MSE)
#       batch_xen_000_x/y/d.npy        <- Xenium batches (resolution=1, CE)
#       states/00/model.ckpt
#       states/01/model.ckpt
#     VIS_P11_LUAD/  XEN_P11_LUAD/
#       embeddings-hist.pickle
#       pred_fullgrid_outputs.pkl
#     results_ex03.pptx
# =============================================================================

set -euo pipefail
export PYTHONWARNINGS="ignore"

CFG="$(dirname "$0")/config.yaml"
# NOTE: All steps auto-discover both VIS* and XEN* samples.
# Preprocessing, predict, and visualize all use auto-discovery.

echo "============================================"
echo " MeowCat Example 3: Visium + Xenium (single pair)"
echo " Config: $CFG"
echo "============================================"

# ---------------------------------------------------------------------------
# Step 1: RCTD deconvolution for Visium
# Activate: conda activate RCTD
# ---------------------------------------------------------------------------
# echo "[Step 1] RCTD deconvolution (Visium only)"
# meowcat rctd --config "$CFG"

# ---------------------------------------------------------------------------
# Step 2: Resolution check (checks all samples matching sample_pattern)
# Activate: micromamba activate rapids_singlecell
# ---------------------------------------------------------------------------
# echo "[Step 2] Resolution check"
# meowcat check-resolution --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3: Preprocess all images (data-agnostic — works for both Visium and Xenium)
# Auto-discovers both VIS* and XEN* samples from data_root.
# Produces single_super_emb.h5ad (UNI histology features) per sample.
# For Xenium, prepare-xenium-batches (Step 4b) will automatically merge
# histology features from single_super_emb.h5ad into the cellbin.
# ---------------------------------------------------------------------------
# echo "[Step 3] Image preprocessing — all samples (VIS* + XEN*)"
# meowcat preprocess --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3.5: Prepare Visium metadata + embeddings
# Creates: anno-names.txt, anno_matrix.tsv, locs.tsv, radius.txt,
#          pixel-size.txt, embeddings-hist.pickle
# ---------------------------------------------------------------------------
# echo "[Step 3.5] Visium metadata preparation"
# meowcat prepare-visium --config "$CFG"

# ---------------------------------------------------------------------------
# Step 4a: Build Visium training batches (batch_vis_*_x/y/d.npy)
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
# echo "[Step 4a] Visium batch preparation"
# meowcat prepare-visium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 4b: Build Xenium training batches (batch_xen_*_x/y/d.npy)
# Both batch_vis_* and batch_xen_* end up in the same batches/ dir.
# The training script identifies data type from the filename prefix.
# Xenium domain IDs continue from where Visium left off (set via
# xenium.visium_batch_dir in config).
# ---------------------------------------------------------------------------
echo "[Step 4b] Xenium batch preparation"
meowcat prepare-xenium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 5: Train the model — 3-phase sequential
# Activate: conda activate he_anno
# Phase 0 (15 ep):  MSE reconstruction pretraining on masked UNI features
# Phase 1 (100 ep): Visium MSE — learns soft cell-type distributions
# Phase 2 (50 ep):  Xenium CE  — fine-tunes to hard single-cell labels
#   encoder is frozen for first freeze_encoder_n=2 layers at each transition
# ---------------------------------------------------------------------------
echo "[Step 5] Training (Recon -> Visium -> Xenium)"
meowcat train --config "$CFG"

# ---------------------------------------------------------------------------
# Step 6: Predict on both samples
# Activate: conda activate he_anno
# Auto-discovers both VIS* and XEN* samples from data_root.
# To override: meowcat predict --config "$CFG" --samples VIS_P11_LUAD,XEN_P11_LUAD
# ---------------------------------------------------------------------------
echo "[Step 6] Prediction — all samples"
meowcat predict --config "$CFG"

echo "[Step 6] Visualization — all samples"
meowcat visualize --config "$CFG"

# ---------------------------------------------------------------------------
# Step 7: Generate PowerPoint summary
# ---------------------------------------------------------------------------
echo "[Step 7] Slide wrap"
meowcat slide --config "$CFG"

echo "============================================"
echo " Done. Outputs: /project/KidneyHE/01_meowcat_test/03_visium_xenium_single/output/"
echo "============================================"
