#!/usr/bin/env bash
# =============================================================================
# Example 2: Train on a single Xenium sample P11_LUAD (hard labels, CE loss)
#
# Training paradigm:
#   Phase 0 (Recon):   reconstruction pretraining (15 epochs)
#   Phase 1 (Xenium):  CE on hard one-hot cell-type labels (100 epochs)
#
# Expected input layout (user-provided):
#   /project/KidneyHE/01_meowcat_test/wrapped_data/02_xenium_only/
#     input/XEN_P11_LUAD/
#       he_raw.<tif|svs>               -> raw H&E image (for meowcat preprocess -> single_super_emb.h5ad)
#       xenium_raw/                    -> raw xenium data (cell_feature_matrix.h5, cells.parquet)
#       adata_cellbin_HistoSweep.h5ad  -> cell-bin location mapping (from external HistoSweep alignment)
#       annotation.csv                 -> cell type annotations (cell_id, cell_state)
#     anno-names.txt                   -> cell type order (referenced by xenium.anno_names_path)
#
# Generated by pipeline:
#     input/XEN_P11_LUAD/
#       single_super_emb.h5ad         -> UNI histology features (Step 3: meowcat preprocess)
#       Xenium_adata_cellbin_analysis_qv20.h5ad  -> cellbin + merged histology_2048 (Step 4)
#       Xenium_adata_cell.h5ad        -> cell data with annotations (Step 4)
# =============================================================================
set -euo pipefail
export PYTHONWARNINGS="ignore"

CFG="$(dirname "$0")/config.yaml"

echo "============================================"
echo " MeowCat Example 2: Xenium-only P11_LUAD"
echo " Config: $CFG"
echo "============================================"

# ---------------------------------------------------------------------------
# Step 1: RCTD — NOT needed for Xenium (hard labels come from annotations)
# ---------------------------------------------------------------------------
echo "[Step 1] Skipped — Xenium data uses hard cell-type labels, no RCTD needed"

# ---------------------------------------------------------------------------
# Step 2: Check image resolution
# NOTE: Commented out — assumes preprocessing was already completed.
# ---------------------------------------------------------------------------
# echo "[Step 2] Resolution check"
# meowcat check-resolution --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3: Preprocess the Xenium H&E image
# NOTE: Commented out — assumes single_super_emb.h5ad already exists.
#   To run from scratch, uncomment the meowcat preprocess line below.
#   The full Xenium preprocessing chain is:
#     1. meowcat preprocess → generates single_super_emb.h5ad (UNI histology features)
#     2. meowcat prepare-xenium-batches → merges single_super_emb.h5ad into cellbin
#        as histology_2048, creates batch_xen_*_x/y/d.npy files
#   NOTE: adata_cellbin_HistoSweep.h5ad (bin-to-pixel location mapping) must be
#   created externally via HistoSweep alignment before running Step 4.
# ---------------------------------------------------------------------------
# echo "[Step 3] Image preprocessing"
# meowcat preprocess --config "$CFG"

# ---------------------------------------------------------------------------
# Step 4: Build training batches (batch_xen_*_x/y/d.npy)
# This runs Part A (h5ad processing) + Part B (batch file creation)
# ---------------------------------------------------------------------------
echo "[Step 4] Xenium batch preparation"
meowcat prepare-xenium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 5: Train the model
# Phases:  Phase 0 (recon, 15 ep) -> Phase 1 (Xenium CE, 100 ep)
# The model operates in sc_only mode (no batch_vis_* files present).
# ---------------------------------------------------------------------------
echo "[Step 5] Training (Recon -> Xenium CE)"
meowcat train --config "$CFG"

# ---------------------------------------------------------------------------
# Step 6: Predict and visualize
# ---------------------------------------------------------------------------
echo "[Step 6] Prediction"
meowcat predict --config "$CFG"

echo "[Step 6] Visualization"
meowcat visualize --config "$CFG"

# ---------------------------------------------------------------------------
# Step 7: Generate PowerPoint summary
# ---------------------------------------------------------------------------
echo "[Step 7] Slide wrap"
meowcat slide --config "$CFG"

echo "============================================"
echo " Done. Outputs: /project/KidneyHE/01_meowcat_test/wrapped_data/02_xenium_only/output/"
echo "============================================"
