#!/usr/bin/env bash
# =============================================================================
# Example 4b: Train on multiple Xenium samples (no Visium)
#             Multi-patient with CDAN cross-patient domain adaptation
#
# Training paradigm:
#   Phase 0 (Recon):   reconstruction pretraining        (15 epochs)
#   Phase 1 (Xenium):  CE on hard one-hot cell-type labels + CDAN (100 epochs)
#
# CDAN aligns patient-level domains (each WSI = one domain) so the encoder
# learns patient-invariant features.
#
# Expected input layout (demo: 4 LUAD patients P11/P17/P19/P24):
#   <data_root>/
#     P11_LUAD_Xenium/                 <- Xenium patient
#       he_raw.tif                     <- raw H&E image
#       xenium_raw/                    <- cell_feature_matrix.h5 + cells.parquet
#       adata_cellbin_HistoSweep.h5ad  <- cell-bin location mapping (slimmed in demo)
#       annotation.csv                 <- cell type annotations (cell_id, cell_state)
#       pixel-size-raw.txt             <- 0.5 µm/px (bundled in demo)
#     P17_LUAD_Xenium/  P19_LUAD_Xenium/  P24_LUAD_Xenium/  ... (same layout)
#   anno-names.txt                     <- cell type order (referenced by xenium.anno_names_path)
#
# Generated by the pipeline (do NOT create manually):
#   single_super_emb.h5ad                    <- UNI histology features (Step 3)
#   Xenium_adata_cellbin_analysis_qv20.h5ad  <- cellbin + merged histology_2048 (Step 4)
#   Xenium_adata_cell.h5ad                   <- cell data with annotations (Step 4)
#
# Expected output layout:
#   <out_root>/
#     mask/
#     batches/
#       batch_xen_000_x/y/d.npy      <- domain 0 (alphabetically first)
#       batch_xen_001_x/y/d.npy      <- domain 1
#       ...
#       states/00/model.ckpt
#       states/01/model.ckpt
#     P11_LUAD_Xenium/  P17_LUAD_Xenium/  ...
#       embeddings-hist.pickle or .npy
#       pred_fullgrid_outputs.pkl
#     results_ex04_multi_xenium.pptx
#
# Usage:
#   conda activate he_anno
#   bash run.sh > log.txt 2>&1 &
# =============================================================================
set -euo pipefail
export PYTHONWARNINGS="ignore"

CFG="$(dirname "$0")/config.yaml"

echo "============================================"
echo " MeowCat Example 4b: Multi-Xenium training"
echo " Config: $CFG"
echo "============================================"

# ---------------------------------------------------------------------------
# Step 1: RCTD — NOT needed for Xenium (hard labels come from annotations)
# ---------------------------------------------------------------------------
echo "[Step 1] Skipped — Xenium data uses hard cell-type labels, no RCTD needed"

# ---------------------------------------------------------------------------
# Step 2: Check image resolution (optional)
# Skipped: the Zenodo demo bundle ships pixel-size-raw.txt per sample.
# For new samples: if you know the H&E resolution, write it (in µm/px) into
# pixel-size-raw.txt in each sample folder. If you DO NOT know it and your
# image is a TIF with embedded resolution metadata, uncomment the following
# code to auto-detect.
# ---------------------------------------------------------------------------
# echo "[Step 2] Resolution check"
# meowcat check-resolution --config "$CFG"

# ---------------------------------------------------------------------------
# Step 3: Preprocess all Xenium H&E images
# Auto-discovers all XEN* samples from project.sample_pattern.
# Can run in parallel on a cluster (one job per sample).
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 3] Image preprocessing — all Xenium samples"
meowcat preprocess --config "$CFG"

# No Visium steps (no prepare-visium, no prepare-visium-batches needed)

# ---------------------------------------------------------------------------
# Step 4: Build Xenium training batches (batch_xen_*_x/y/d.npy)
# Domain IDs start from 0 (visium_batch_dir: null).
#   For the demo: P11_LUAD_Xenium=0, P17_LUAD_Xenium=1, P19_LUAD_Xenium=2, P24_LUAD_Xenium=3.
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 4] Xenium batch preparation"
meowcat prepare-xenium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 5: Train — Recon + Xenium CE + CDAN
# Activate: conda activate he_anno
# Phase 0 (15 ep):   reconstruction pretraining
# Phase 1 (100 ep):  Xenium CE + CDAN domain adversarial (adv_lambda=0.005)
# ---------------------------------------------------------------------------
echo "[Step 5] Training (Recon -> Xenium CE + CDAN)"
meowcat train --config "$CFG"

# ---------------------------------------------------------------------------
# Step 6: Predict and visualize on all Xenium samples
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 6] Prediction — all samples"
meowcat predict --config "$CFG"

echo "[Step 6] Visualization — all samples"
meowcat visualize --config "$CFG"

# ---------------------------------------------------------------------------
# Step 7: Generate PowerPoint summary
# ---------------------------------------------------------------------------
echo "[Step 7] Slide wrap"
meowcat slide --config "$CFG"

echo "============================================"
echo " Done. Outputs: <DEMO_DATA_ROOT>/04_multi_xenium/output/"
echo "============================================"
