#!/bin/bash

# =============================================================================
# 
# Example 4b: Train on multiple Xenium samples (no Visium)
#             Multi-patient with CDAN cross-patient domain adaptation
#             4 LUAD samples: P24, P19, P17, P11
#
# Training paradigm:
#   Phase 0 (Recon):   reconstruction pretraining        (15 epochs)
#   Phase 1 (Xenium):  CE on hard one-hot cell-type labels + CDAN (100 epochs)
#
# CDAN aligns patient-level domains (each WSI = one domain) so the encoder
# learns patient-invariant features.
#
# Prerequisites:
#   - Run setup_data.sh first to create symlinks
#   - single_super_emb.h5ad is pre-prepared (Steps 1-3 skipped)
#
# Expected input layout (created by setup_data.sh):
#   /project/KidneyHE/01_meowcat_test/04_multi_xenium/input/
#     P24_LUAD_Xenium/                 <- Xenium patient 1
#       xenium_raw/                    <- 10x Xenium output (symlinked)
#       adata_cellbin_HistoSweep.h5ad  <- cell-bin location mapping (symlinked)
#       annotation.csv                 <- cell type annotations (symlinked)
#       single_super_emb.h5ad          <- UNI histology features (pre-prepared, symlinked)
#     P19_LUAD_Xenium/                 <- Xenium patient 2  (same layout)
#     P17_LUAD_Xenium/                 <- Xenium patient 3  (same layout)
#     P11_LUAD_Xenium/                 <- Xenium patient 4  (same layout)
#     anno-names.txt                   <- cell type order (8 coarse types)
#
# Generated by pipeline:
#     P*_LUAD_Xenium/:
#       Xenium_adata_cellbin_analysis_qv20.h5ad  <- cellbin + merged histology_2048 (Step 4)
#       Xenium_adata_cell.h5ad                   <- cell data with annotations (Step 4)
#
# Expected output layout:
#   /project/KidneyHE/01_meowcat_test/04_multi_xenium/output/
#     batches/
#       batch_xen_00{0,1,2,3}_x/y/d.npy  <- 4 samples (domain 0-3)
#       states/00/model.ckpt
#       states/01/model.ckpt
#     P*_LUAD_Xenium/
#       embeddings-hist.pickle
#       pred_fullgrid_outputs.pkl
#     results_ex04_multi_xenium.pptx
# =============================================================================
set -euo pipefail
export PYTHONWARNINGS="ignore"

CFG="$(dirname "$0")/config.yaml"

echo "============================================"
echo " MeowCat Example 4b: Multi-Xenium training"
echo " Config: $CFG"
echo "============================================"

# ---------------------------------------------------------------------------
# Steps 1-3: SKIPPED
# - Step 1 (RCTD): not needed for Xenium (hard labels from annotation.csv)
# - Steps 2-3 (preprocess): single_super_emb.h5ad is pre-prepared
# ---------------------------------------------------------------------------
echo "[Steps 1-3] Skipped — single_super_emb.h5ad is pre-prepared"

# ---------------------------------------------------------------------------
# Step 4: Build Xenium training batches (batch_xen_*_x/y/d.npy)
# Domain IDs start from 0 (visium_batch_dir: null).
#   domain 0 -> P24, domain 1 -> P19, domain 2 -> P17, domain 3 -> P11
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 4] Xenium batch preparation"
meowcat prepare-xenium-batches --config "$CFG"

# ---------------------------------------------------------------------------
# Step 5: Train — Recon + Xenium CE + CDAN
# Activate: conda activate he_anno
# Phase 0 (15 ep):   reconstruction pretraining
# Phase 1 (100 ep):  Xenium CE + CDAN domain adversarial (adv_lambda=0.005)
# ---------------------------------------------------------------------------
echo "[Step 5] Training (Recon -> Xenium CE + CDAN)"
meowcat train --config "$CFG"

# ---------------------------------------------------------------------------
# Step 6: Predict and visualize on all Xenium samples
# Activate: conda activate he_anno
# ---------------------------------------------------------------------------
echo "[Step 6] Prediction — all samples"
meowcat predict --config "$CFG"

echo "[Step 6] Visualization — all samples"
meowcat visualize --config "$CFG"

# ---------------------------------------------------------------------------
# Step 7: Generate PowerPoint summary
# ---------------------------------------------------------------------------
echo "[Step 7] Slide wrap"
meowcat slide --config "$CFG"

echo "============================================"
echo " Done. Outputs: /project/KidneyHE/01_meowcat_test/04_multi_xenium/output/"
echo "============================================"
